

import type { Metadata } from "next";

import { Header } from "../../../_components/Header";
import { OverlayProvider } from "@/contexts/OverlayContext";
import { RenderSidebar } from "../../../_components/RenderSidebar";
import { OverlayRoot } from "@/_components/OverlayRoot";


export const metadata: Metadata = {
  title: "painel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children?: React.ReactNode;
}>) {
 return (
    <html lang='pt-BR'>
      <body
        className="antialiased" >
        <div className="h-screen flex overflow-hidden flex-col w-full">
          <OverlayProvider>
          <OverlayRoot/>
            <Header />
            <div className="flex overflow-hidden max-h-screen">
              <RenderSidebar />
              {children}
              </div>
          </OverlayProvider>
        </div>
      </body>
    </html>
  );
}


/*  gridTemplateAreas: `
            "header header header "
            "sidebar feed feed "
            "sidebar feed feed "
           `,
<div style={{ gridArea: "header", background: "#facc15" }}><Header/></div>
            <div style={{ gridArea: "sidebar", background: "#f87171" }}><Sidebar/></div>
            <div style={{ gridArea: "feed", background: "#60a5fa" }}>{children}</div>
           */
