import type { Metadata } from "next";
import { Sidebar } from "./_components/Sidebar";
import { Header } from "./_components/Header";


export const metadata: Metadata = {
  title: "painel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body
        className="antialiased" >
         <div className="h-screen flex flex-col w-full">
            <Header/>
              <div 
                className="flex h-full"
                >
               <Sidebar/>
                {children}
              </div>
          </div>
      </body>
    </html>
  );
}


/*  gridTemplateAreas: `
            "header header header "
            "sidebar feed feed "
            "sidebar feed feed "
           `,
<div style={{ gridArea: "header", background: "#facc15" }}><Header/></div>
            <div style={{ gridArea: "sidebar", background: "#f87171" }}><Sidebar/></div>
            <div style={{ gridArea: "feed", background: "#60a5fa" }}>{children}</div>
           */
